### ISSUE TITLE
Vertical Driver's Licenses

### ISSUE THREAD

**Issue by ninjudd** [BlinkID/blinkid-ios#139]
Many US states use vertical licenses for people under 21. It seems that BlinkID has trouble recognizing
the front of these licenses.

https://www.dmv.ca.gov/portal/wcm/connect/e090f7ec-64bc-4e87-afc8-e66895903b37/dl627e.pdf?MOD=AJPERES

Is there a way to enable this in the SDK?

Or is there a best practice for getting it to work? Should users hold the card vertically, or rotate it horizontally?

**Comment by DoDoENT** [comment]
Hi @ninjudd!

When using [PPDetectorRecognizer](http://cocoadocs.org/docsets/PPBlinkID/2.13.0/Classes/PPDetectorRecognizerSettings.html) configured with [PPDocumentDetector](http://cocoadocs.org/docsets/PPBlinkID/2.13.0/Classes/PPDocumentDetectorSettings.html) configured with [PPDocumentSpecification](http://cocoadocs.org/docsets/PPBlinkID/2.13.0/Classes/PPDocumentSpecification.html) created with [PPDocumentPresetId1Card](http://cocoadocs.org/docsets/PPBlinkID/2.13.0/Constants/PPDocumentPreset.html), it will only be able to detect horizontal cards.

In order to detect vertical cards, you should use [PPDocumentPresetId1VerticalCard preset](http://cocoadocs.org/docsets/PPBlinkID/2.13.0/Constants/PPDocumentPreset.html).

You can also activate [multiple presets](http://cocoadocs.org/docsets/PPBlinkID/2.13.0/Classes/PPDocumentDetectorSettings.html#//api/name/setDocumentSpecifications:) at the same time, however detection accuracy will then be lower for both presets.

**Comment by culoi** [comment]
Closing the issue. Please reopen if you need additional help on this.
