### ISSUE TITLE
New 2018 California Driver's License

### ISSUE THREAD

**Issue by Kiplol** [BlinkID/blinkid-ios#151]
We've been unable to successfully scan the barcode of the new format California driver's licenses that began being issued January 22, 2018.  We've added manual entry options to get around this, but are there plans in the works to support these new licenses?

**Comment by culoi** [comment]
Hello @Kiplol 

Can you please share which version of the SDK are you using? 

We are able to scan new version of the CA DL (Real ID) without the problem.

Regards,

Ivan

**Comment by Kiplol** [comment]
Hi Ivan,

I'm using version 2.16.0.  I'm using an instance of PPUsdlRecognizerSettings as the scan settings of the camera coordinator.

**Comment by luanpv87** [comment]
I'm using version 2.9 and i see this issue too

**Comment by jcular** [comment]
Hi @luanpv87,

some DLs have smaller barcodes on the back side that makes it difficult to read them on phones with smaller screens since the UI will tell the user to keep the phone further from the barcode. Try to close up on the barcode. You can try setting the cameraPreset to Max if you need to really close up on the barcode to scan it. If camera preset doesn't help then switching Overlay UI from portrait to landscape might help. Please let us know if this helps.

Kind regards,
Jure
