### ISSUE TITLE
Detect if Passport vs Driver's license face

### ISSUE THREAD

**Issue by joshuawright11** [BlinkID/blinkid-ios#161]
I am trying to create a flow where the user holds up either a passport or the face of a driver's license and we then take action based off of whether Microblink detects a passport or a driver's license.

I tried using the following as setup for the `PPCoordinator`:
```swift

// Drivers License recognizer
let documentFront = PPDocumentFaceRecognizerSettings()       
documentFront.returnFullDocument = true            
settings.scanSettings.add(documentFront)            
            
// License recognizer
let passportDetector = PPMrtdRecognizerSettings()            
passportDetector.dewarpFullDocument = true            
settings.scanSettings.add(passportDetector)

func coordinator(_ coordinator: PPCoordinator!, didOutputResults results: [PPRecognizerResult]!) {

        // Block 1
        if let result = results.filter({ $0 is PPDocumentFaceRecognizerSettings}).first,
            let typedResult = result as? PPDocumentFaceRecognizerSettings {
            // The document is a license front
        }

        // Block 2
        if let result = results.filter({ $0 is PPMrtdRecognizerResult}).first,
            let typedResult = result as? PPMrtdRecognizerResult {
            // The document is a passport
        }
}

```

However, it seems as though the `PPDocumentFaceRecognizerSettings` recognizes the passport. And so when scanning a passport, `Block 1` is called, with `Block 2` also sometimes being called. Is there some recognizer that will only detect the front of a US Driver's license (not a passport) so that I can accomplish this?

**Comment by Pickles112358** [comment]
Hi @joshuawright11 

Unfortunately, SDK cannot stop Document Face Recognizer from recognizing front side of the passport. However, you could do few things to improve your accuracy.

One solution that comes to mind is to ignore PPDocumentFaceDetectorResult until it is recieved specific number of times. For example, you could have a counter in _didOutputResults_ method which counts how many times in a row PPDocumentFaceDetectorResult appeared **WITHOUT** PPMrtdRecognizerResult. In case of driver's license, PPMrtdRecognizerResult will never be outputted, and in case of passport it highly likely that it will be outputted together with PPDocumentFaceRecognizerResult let's say once in three scans.

One other thing that I have noticed is that in your code:
```swift
        // Block 1
        if let result = results.filter({ $0 is PPDocumentFaceRecognizerSettings}).first,
            let typedResult = result as? PPDocumentFaceRecognizerSettings {
            // The document is a license front
        }
```

you are using PPDocumentFaceRecognizerSettings instead of PPDocumentFaceRecognizerResult. I don't think you are getting desired behaviour this way.

Let me know if this helps!
Dino

**Comment by culoi** [comment]
Closing the issue. Please reopen if you have additional question or contact us directly at support@microblink.com
