### ISSUE TITLE
Feature Request: Localization

### ISSUE THREAD

**Issue by rostislawko** [BlinkID/blinkid-ios#179]
Right now BlinkID SDK only supports English localization. And if phone uses not English localization, on the screen appear only localization keys. I propose to change SDK localization policy by implementing one of two possible choices:
1. (I wish you implement it) - add localization for the most popular languages.
2. (not the best choice, but it will fix localization issue with non-english languages. Just to remove English localization file, or to hardcode strings without referencing to NSLocalizedString(). 

I found temporarily workaround with localization issue: 
`
MBDocumentOverlaySettings *settings = [[MBDocumentOverlaySettings alloc] init];
settings.language = @"en";
`

**Comment by mparadina** [comment]
Hi @rostislawko 

Hope you are well!

Just wanted to inform you that we have translated our SDK to the following languages: **Croatian, Czech, English, French, German, Italian, Portuguese, Slovak, and Spanish** in version 5.6.

In case of any additional questions, feel free to ask or contact us directly at support@microblink.com

Regards,
Milan

**Comment by MoathOthman** [comment]
@mparadina hey , am using PPBlinkID version 5.9.0 , and when the language of the app is Arabic , am not getting the translation correctly , am getting something like [[blinkid_generic_message]].  
and [[mb_unsuppored_document_title]] . 
Although I checked that you have the Localizable.strings for arabic. but its ar-AE.strings , it should be ar.strings because ar-AE is specific for certain region   "UAE" . 

So as a solution , u just need to rename the file, I did not make a PR because I see its automated process. 

Thank you

**Comment by mparadina** [comment]
Hi @MoathOthman 

Just to confirm, if you put the language to "ar-AE" in the project, will you be getting the Arabic translation?

You can, for instance, place the language method before you initialize the scanning process like this:
`MBMicroblinkApp.instance.language = "ar-AE"`   

Also to ask, does the translation convert to Arabic when you put the device's language to Arabic (without placing the method mentioned above)?

Regards,
Milan

**Comment by MoathOthman** [comment]
hey @mparadina 
"Also to ask, does the translation convert to Arabic when you put the device's language to Arabic (without placing the method mentioned above)?"
for me no, since am not in UAE. 

"
Just to confirm, if you put the language to "ar-AE" in the project, will you be getting the Arabic translation?

You can, for instance, place the language method before you initialize the scanning process like this:
MBMicroblinkApp.instance.language = "ar-AE"
"
I have not tried that, what I did is renaming ar-AE.strings to ar. strings and it worked fine since it has no region constraints.

**Comment by mparadina** [comment]
HI @MoathOthman 

Understood!

We will take your suggestion into consideration for the upcoming releases.

Let us know if any additional questions come up.

Regards,
Milan

**Comment by MoathOthman** [comment]
Thank you a lot Milan for the support and follow-up.

Best.

**Comment by mijo-gracanin** [comment]
Hi @MoathOthman,

In v5.10, we made English the fallback language so that you don't see localization keys (text like `[[blinkid_generic_message]]`).
From BlinkID v5.12, "ar-AE" will be the fallback language for all untranslated Arabic dialects. I hope that this solution works for you and that it's a generally acceptable solution. The reason why we use "ar-AE" specifically is that that's what our translation service provided when we requested Arabic translation.
