### ISSUE TITLE
OCR Debug Image for BlinkID 4.0

### ISSUE THREAD

**Issue by Jovial-Ionnex** [BlinkID/blinkid-ios#188]
Dear Microblink,

As our company has decided to migrate to version 4.0, we found out that certain features was removed as per quote below.
> There is no longer a [didOutputMetadata] delegate method. Instead, there is a separate delegate for every metadata item that can be obtained during processing. In this way, it is now more clear which methods need to be implemented if specific metadata needs to be obtained.

While we did not exactly have issue regarding the changes, however, we have trouble in debugging the templating API as the change that you have made does not include on how to obtained the Metadata needed for Debugging as shown on your previous version below.
`let settings: PPSettings = PPSettings(resourceBundle: Bundle(path: path)!)`
`settings.metadataSettings.debugMetadata.debugOcrInputFrame = true`
`settings.licenseSettings.licenseKey = MBLicense`
`settings.metadataSettings.dewarpedImage = true`

While we found a workaround for this is coded as below.
`let faceImage = MBImageReturnProcessor()`
`faceImage?.encodeImage = true`
`let faceImageProcesorGroup = MBProcessorGroup(processingLocation: CGRect(x: 55.0/85.0, y: 12.0/54.0, width: 28.0/85.0, height: 34.0/54.0), dewarpPolicy: MBDPIBasedDewarpPolicy(desiredDPI: 400), andProcessors: [faceImage!])`

While the above might seems working, however, technically speaking we have to code every `MBImageReturnProcessor()` for every OCR Image that we want to debug.
Hence, we were wondering how exactly your new MetaData is implemented.

Best Regards,

Jovial

NB: Your example did not show how this is implemented nor your documentation did stated on how to perform this.

**Comment by DoDoENT** [comment]
> While we found a workaround for this is coded as below.

>     let faceImage = MBImageReturnProcessor()
>     faceImage?.encodeImage = true
>     let faceImageProcesorGroup = MBProcessorGroup(processingLocation: CGRect(x: 55.0/85.0, y: 12.0/54.0, width: 28.0/85.0, height: 34.0/54.0), dewarpPolicy: MBDPIBasedDewarpPolicy(desiredDPI: 400), andProcessors: [faceImage!])

> While the above might seems working, however, technically speaking we have to code every MBImageReturnProcessor() for every OCR Image that we want to debug.
> Hence, we were wondering how exactly your new MetaData is implemented.

Behind the scenes the MetaData is implemented similarly as before, but the public API now reflects the ideas behind the scenes, instead of masking them with opaque booleans. Before v4.0.0, when you enabled debug metadata, we needed to perform the same, without actually knowing which images are you actually interested in - so we enabled all of them, thus drastically degrading performance and increased debuggability complexity.

Now, although it seem more complex for you at the first try, you actually have much more flexibility because you can now install `ImageReturnProcessor` to the exact same group that performs the OCR - you do not need to create separate processor group. By having the `ImageReturnProcessor` in the same processor group as your `ParserGroupProcessor`, you have the ability to obtain exactly the same image that was OCR-ed (which was not always the case before) and, furthermore, you can install `ImageReturnProcessor` only to processor groups that you wish to debug, so you get more precise debug information, because you know exactly which image did you receive, unlike before when you had to ensure different names for different parser groups.

I agree that we need to improve documentation about debugging Templating API code. @Pickles112358 and @juraskrlec will handle this in future releases.
