### ISSUE TITLE
Date issue

### ISSUE THREAD

**Issue by danielbotka** [BlinkID/blinkid-ios#192]
Hey, I have some issues with proper date format, can't understand what really is happening under the hood.

I have a Croatian ID, that has a birthday: 26.02.1992., and a date of expiry: 01.06.2023.

For this, the library parses the following:
recognizerResult.dateOfBirth: 1992-02-25 23:00:00 +0000
recognizerResult.dateOfIssue: 2018-05-31 22:00:00 +0000
recognizerResult.dateOfExpiry: 2023-05-31 22:00:00 +0000

As far as I understand, this is UTC, and date of birth seems to be fine, as Croatia is GMT+1 generally (GMT+2 at the moment, aka CEST) the date of issue and date of expiry will not work, when CEST becomes CET again.

I suspect that the problem is that the retrieved date from OCR is depending on the phone's local, but it should not.

So my question is really, why do we have 1 hour differences between date of birth and date of expiry? What do you suggest to have the correct date, that is presented on the ID?

Thanks,

Daniel

**Comment by dCubelic** [comment]
Hi,

the scanned dates are always saved using the current time zone, but the Date object always represents dates using UTC which results in dates you got.
The difference of 1 hour between dateOfBirth and dateOfExpiry is simply there because on 26.02.1992. the DST was not active, and on 01.06.2023. it should be.

Just using the default iOS Date and Calendar objects you should get the correct date, because it takes current locale into account when displaying it, but printing the date in log will print the UTC version.

I hope this answers your question. If you have any more questions, feel free to contact us.

Best regards,

Dominik

**Comment by danielbotka** [comment]
Hi,

Yes, but that's exactly my problem. I don't think a scanned date should actually use any locale, as it will trick the real UTC value. I believe that the date we see on any ID is in UTC, because if it would depend on any local, probably there will be exact time and indication for +/-.  It should be scanned as UTC, and if needed, it can be transformed depending on the requirements, eg. to a specific locale.

Anyways, thank you, at least I understand now how it works.

Can you tell me what's the reason behind using phone locale?

Thanks,

Daniel

**Comment by dCubelic** [comment]
Hi,

This is just the convention we've used. Since NSDate always has a time zone associated with it, we've chosen to use the current time zone, not UTC. The only thing that is important to you is that you take that into account when you convert NSDate into String.

Regards,
Dominik

**Comment by danielbotka** [comment]
Yes, that was actually the case. But because of this, I think in midterm it can cause problems, eg. especially if you actually persist the date, the actual NSDate object, and you travel for an other country, it can surprise you because UTC is not correct.

But anyways, I got your point, it can be argued from different perspectives what would the best, and probably just have to come up with an approach and be consistent. I can work with this information, so closing it.

Thanks,
Daniel
