### ISSUE TITLE
Migration to 4.1

### ISSUE THREAD

**Issue by yaakovgamliel** [BlinkID/blinkid-ios#213]
Hi,
We have been using the SDK for over a year and a half with very good results, right now we are starting the migration process to the newest SDK version, the most challenging part has been trying to keep the same behavior specifically navigation, our app work as a navigation controller where every new screen is pushed in to the stack, the problem is that we use to push a new controller after a successful pdf417 scan completed, with the current SDK the controller being pushed look like this:

MBViewControllerFactory.recognizerRunnerViewController(
            withOverlayViewController: customOverlayViewController)

it is completely abstracted so when a scan happens it is the customOverlayViewController the one
that handles the results, not the presenting controller neither the controller that pushed so customOverlayViewController is not part of the stack anymore and consequently it can't push the next controller which will present the scanned results.
The result we would like to achieve is the following:
scan button pressed --> push controller with custom overlay ---> succeful scan is found --> push details controller to display scanned information.
Is there any way we could keep this behavior with the new SDK?

Thanks

**Comment by jcular** [comment]
Hi @yaakovgamliel,

there shouldn't be an issue with this flow.
So when you start scanning, you push the `ReocgnizerRunnerViewController` which is created using `MBViewControllerFactory.recognizerRunnerViewController(withOverlayViewController: customOverlayViewController)`.
When the scan is successful you can push result view controller too.

If I understand correctly the issue is that your custom overlay handles the results.
Custom overlay view controller doesn't have to be the one to handle the results, your presenting view controller can handle the results it just needs to implement `MBScanningRecognizerRunnerViewControllerDelegate` and you need to set `customOverlayViewController.scanningRecognizerRunnerViewControllerDelegate = presentingViewController`. Or you can add a delegate that returns the results to the presenting view controller and it can create resultViewController and present it.

New SDK allows you to keep the same behaviour, I'd just suggest that you migrate to 4.3, there are no API changes between 4.1 and 4.3, but 4.3 contains bugfixes and better support for iPhone Xs, Xr, Xs max models.

Let us know if this helps.

**Comment by yaakovgamliel** [comment]
Thank you for the fast response, I'll try out your suggestion and let you know how its goes

**Comment by yaakovgamliel** [comment]
It worked using the overlay controller as the one pushing, thank you
