### ISSUE TITLE
Type 'ViewController' does not conform to protocol 'PPScanningDelegate' 

### ISSUE THREAD

**Issue by YogeshBharate** [BlinkID/blinkid-ios#218]
I have integrated the BlinkID in my application and I have already implemented the following mandatory methods:

func scanningViewControllerUnauthorizedCamera(_ scanningViewController: UIViewController) {}

func scanningViewController(_ scanningViewController: UIViewController, didFindError error: Error) {}

func scanningViewControllerDidClose(_ scanningViewController: UIViewController) {}

func scanningViewController(_ scanningViewController: UIViewController?, didOutputMetadata metadata: PPMetadata) {}

func scanningViewController(_ scanningViewController: UIViewController?, didOutputResults results: [PPRecognizerResult]){}

Still I am facing the error "Type 'ViewController' does not conform to protocol 'PPScanningDelegate' Error" and Type 'ViewController' does not conform to protocol 'PPScanningDelegate'.

In my another app still its working fine, but when I start to integrate in new app, it gives me above error.

Is there any extra setting or framework required to resolve this issue.

Type 'ViewController' does not conform to protocol 'PPScanningDelegate' for this error when we add protocol stubs? Its add following three methods

func scanningViewControllerUnauthorizedCamera(_ scanningViewController: UIViewController & PPScanningViewController) {}
func scanningViewController(_ scanningViewController: UIViewController & PPScanningViewController, didFindError error: Error) {}
func scanningViewControllerDidClose(_ scanningViewController: UIViewController & PPScanningViewController) {}

Thanks in advance ,please let me know how to resolve this issue. Why this issue occures ?

**Comment by jcular** [comment]
Hi @YogeshBharate,

`func scanningViewControllerUnauthorizedCamera(_ scanningViewController: UIViewController) {}` and 
`func scanningViewControllerUnauthorizedCamera(_ scanningViewController: UIViewController & PPScanningViewController)` are the same method, the second one has scanningViewController defined as `UIViewController` that conforms to `PPScanningViewController` protocol.
These might happen because of the changes in Swift versions, so if your app was written in an older version of Swift it might have different protocol stubs since they are translated from objective-c.
Notice that the only difference in methods is `& PPScanningViewController `. I suggest that you just transfer your logic from older methods to corresponding new ones.

Kind regards,
Jure

**Comment by YogeshBharate** [comment]
Thank you for the reply !!! 
Currently, I am using blinkId Version 4.3.0
