### ISSUE TITLE
Progress Bar and Camera mode

### ISSUE THREAD

**Issue by ghost** [BlinkID/blinkid-ios#231]
Hi All,

I need to have a progress bar for the scanning and also at anytime user can be allowed to click the Camera button in the CustomOverlay and capture the image and leave scanning page.

Regards,
Vishwa

**Comment by jcular** [comment]
Hi AcceonMaster,

currently, I don't see a way to add a progress bar for the scanning since no progress is being reported other than if the state is valid, empty or uncertain.
In our default overlays we don't add buttons to capture the image, if you are using custom overlays you can add and implement the button easily into your custom overlay. To capture the image you can call the `captureHighResImage` on `RecognizerRunnerViewController`.

Kind regards,
Jure

**Comment by Cerovec** [comment]
Hi @ghost,

We're closing this as this falls in the category of Custom UI integration.

Please let us know if we can do anything else to help.

Best,
Jurica.
