### ISSUE TITLE
Unhandled exception when license key is not valid

### ISSUE THREAD

**Issue by denismullaraj** [BlinkID/blinkid-ios#259]
#208 
# [REQUIRED] Step 2: Describe your environment

  * Xcode version: 10.2.1
  * BlinkID SDK version: 4.11.0
  * What are you trying to scan? ID Document

### [REQUIRED] Step 3: Describe the problem
Putting an invalid license key throws an exception and it wasn't really clear to me when calling `MBMicroblinkSDK.sharedInstance().setLicenseKey("license-key-value")` that it could throw an exception, until I tested out and my app crashed. Btw, the license key I used, is an old license key that I am using right now in version 2.9.0 of BlinkID for iOS in my production code base and it's working. Now that I am upgrading the library to 4.11.0 and using the old license key I get:

> *** Terminating app due to uncaught exception 'MBInvalidLicenseKeyException', reason: 'Your license key is invalid! Invalid license buffer size: 53'

I also checked the exception you handle, and I saw two exception that look similar but I am not sure why one has an extra "e" in `MBException.h` there is `MBInvalidLicenseKeyException` and `MBInvalidLicenseeKeyException`, why is that?

So in general I am looking to understand **how to handle exceptions when setting the license key**, and **what does that extra "e" in the second exception means**.

**Comment by culoi** [comment]
Hi @denismullaraj 

Major changes were introduced in v4.x.x of our SDK. I suggest that you read the article written by our dev team if you are interested in more information: https://microblink.com/blog/major-change-of-the-api-and-in-the-license-key-formats

So you are not able to use the key for v1 (v2.xx.x of BlinkID SDK) in v2 (v4.x) as license key format changed. New license key format is base64 string, while the old API key was 8 blocks of 8 characters.

Regarding the license key exception, this is set by design. Before, in old API, if you had multiple recognizers set, you didn't know that until someone opened scanning for that specific recognizer. This was a huge problem for some users that went live and didn't have time for proper testing. So all the sudden, their app is crashing in the production. In new API, we are now crashing the app if you set recognizers that are not supported by the license key. This helps us to avoid situations like we had in the old API. 

As you are probably familiar, we have multiple ways of setting the licenses key. 
One of the ways is to set both license key and licensee (which is an application identifier for which the key is generated). This option allows users that implement our SDK inside their SDK            in the library mode, for example when our SDK is being packaged inside 3rd party SDK. Unlocking Microblink SDK in library mode allows usage of single license within multiple application packages.

Hope this helps you understand the processes and exceptions. 

Regards

**Comment by denismullaraj** [comment]
Thank you, although I still haven't received an answer for what I am asking: **How can I handle exception when setting license key?** I receive the license key from a server call, and I would like to be sure the app doesn't crash if the license is not right.

**Comment by denismullaraj** [comment]
@culoi Can you please let me know how to handle exception in this case?

**Comment by culoi** [comment]
Hi @denismullaraj 

As explained before, we crash the app on purpose and throwing the MBInvalidLicenseKeyException in order to avoid the problems from the old API. You can try to catch the exception, but we are crashing the SDK on purpose. All this is avoided by using the correct license key and using only recognizers that are enabled for it. 

Here is an article that can help you to catch the exception in Swift: https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html

**Comment by denismullaraj** [comment]
So if I have an issue in the server that is sending to some users only the license key, that means that my app will crash. But I would like to prevent it and maybe disable some functionality if it crashes through error handling. I'll take a look at the link you provided!

**Comment by denismullaraj** [comment]
@culoi I can't find out how to handle the exception. I would like to catch it and do something else, not crash my app.

**Comment by culoi** [comment]
Hi @denismullaraj 

Can you please share the progress that you made on handling the exception? 

You can set it in the following way:

> @try {
            // methode for unlocking the key
        }
        @catch (NSException *exception) {
            NSLog(@"Problem!!! Caught exception: %@", [exception name]);
        }`

**Comment by denismullaraj** [comment]
Hi @culoi that is valid only for Objective C codebase, I am running in a Swift codebase, but anyway, I already tried since I understood I needed to handle Objective C exceptions in Swift in my case, I tried to make an Objective C helper to catch exceptions, included Objective C files (.h and .m) in the bridge header of my app project, but still it throws the exception without catching it and it just crash the app.

If I am not wrong, there were other issues opened with this same request I am trying to ask, but none has been resolved publicly. 

Is there any way to solve this? I don't want my app to crash if the key is not valid, I just want to know it, catch it, and do something proper to the User Experience of my users.

**Comment by denismullaraj** [comment]
I tried 

ObjcCatcher.h
```
#import <Foundation/Foundation.h>
@interface ObjcCatcher : NSObject
+ (BOOL)performBlockCatchingException:(void(^)(void))tryBlock error:(__autoreleasing NSError **)error;
@end
```

ObjcCatcher.m
```
#import "ObjcCatcher.h"
@implementation ObjcCatcher 
+ (BOOL)performBlockCatchingException:(void(^)(void))tryBlock error:(__autoreleasing NSError **)error {
    @try {
        tryBlock();
        return YES;
    }
    @catch (NSException *exception) {
        *error = [[NSError alloc] initWithDomain:exception.name code:0 userInfo:exception.userInfo];
        return NO;
    }
}
@end
```

Imported in my `*-Bridging-Header.h`.

Used it:
```
do {
    try ObjcCatcher.performBlockCatchingException {
          MBMicroblinkSDK.sharedInstance().setLicenseKey("invalid-license-key")
    }
}
catch {
    print("An error ocurred")
}
```

**Comment by lucas-kummerle-perger** [comment]
Considering the exception is also thrown when a licence expires it probably makes more sense to throw an error instead which can then be caught in Swift. I think an exception is not obvious from the function documentation. A consuming application probably would want to recover from this instead of crashing their application.

**Comment by Cerovec** [comment]
Hi Lucas,

It was our internal policy to insist on crashing the app if a developer error occurred. Invalid license key is a developer error because the scanning cannot continue. For example, an integrator of our SDK might catch the exception so the user would not see the crash, but that user would not be able to do scanning - effectively rendering our SDK completely unusable for them. This case we want to avoid.

However, we're revisiting this specifically for license keys as there are legitimate use cases where catching the error is necessary. 

We're classifying this issue as enhancement and let you know what we decide and when we decide to make the change.

Thanks,
Jurica.

**Comment by mparadina** [comment]
Hello @denismullaraj and @lucas-kummerle-perger 

Hope you are well and safe.

I just wanted to inform you that, from version 5.6, you can now catch the exception when trial keys expire or when they are invalid.

Also, in case of any additional questions, feel free to ask here or contact us directly at support@microblink.com

Regards,
Milan

**Comment by mparadina** [comment]
Hello @denismullaraj and @lucas-kummerle-perger

Just following up on this thread.

Did you manage to try to catch the mentioned exception with version 5.6 or above?

Regards,
Milan

**Comment by denismullaraj** [comment]
@mparadina Hi! I'm currently not working on that project anymore. But thanks for the update, I'm pretty sure some will benefit from having the ability to catch the exception now. Regards, Denis
