### ISSUE TITLE
Capturing the emirates ID with different Front and Back images without throwing error.

### ISSUE THREAD

**Issue by phanikumar560** [BlinkID/blinkid-ios#263]
Hi Team,

Used Blink ID IOS version 4.8 for building library for cross platform application.
There are some scenarios where Blink ID library is capturing the emirates ID with different Front and Back images without throwing any error.
Tried with Blink ID IOS version 4.11 still facing the same issue.
Please help out in this regard.
Please let us know if anything is required.

Thanks
Phani

**Comment by Cerovec** [comment]
Hi @phanikumar560,

Sorry for such a long wait for the answer, we deeply apologize for that.

Can you elaborate a bit more on the issue? What does "different front and back images" mean? Do you mean that you are able to scan a front image from one ID, and back image from another ID?

Please give us some more information so that we can understand the issue better.

Thanks!
Jurica.

**Comment by Cerovec** [comment]
HI @phanikumar560,

we're closing this issue at this moment because, in our understanding, this has already been solved. We have "data matching" functionality in place since v5.0, which checks whether the front and the back side of the scanned ID belong to the same actual physical ID.

If this is not the actual original issue, or you need help to get it working, please reopen the issue.

Thanks,
Jurica.
