### ISSUE TITLE
Model signature verification failed!

### ISSUE THREAD

**Issue by vg-identance** [BlinkID/blinkid-ios#271]
We notice that sometimes Microblink SDK crashes during verification process with next logs:

```
[E] func [line:173] 2019-11-08 16:46:13.762722+0200 REDACTED[1771:418085] Unable to reserve address space
[E] func [line:427] 2019-11-08 16:46:13.762868+0200 REDACTED[1771:418085] Model signature verification failed!
```

I don't know exact way to reproduce. It is very rare crash case, always happening at the beginning of recognizing process

Last time it is happened on iPhone 6 Plus iOS 12.4.3 with SDK 4.11

[microblink crash.log](https://github.com/BlinkID/blinkid-ios/files/3825073/microblink.crash.log)

<img width="360" alt="Screen Shot 2019-11-08 at 16 55 41" src="https://user-images.githubusercontent.com/49786280/68486094-1e279480-0249-11ea-82a4-e4737447c746.png">
<img width="880" alt="Screen Shot 2019-11-08 at 16 47 47" src="https://user-images.githubusercontent.com/49786280/68486176-431c0780-0249-11ea-80e0-266da8e44e0d.png">

**Comment by DoDoENT** [comment]
This can happen when application fragments the virtual memory before invoking the recognition so much that our engine cannot reserve contiguous address space (virtual memory) required for recognition.

In upcoming BlinkID v5.1 we changed a bit the address space allocation strategy, which should, in theory, reduce the chance of such error, but the general problem is that there is not enough memory for performing the recognition, i.e. the address space is too fragmented. This usually happens if the application performs lots of small allocations before invoking the recognition.

As a workaround, you can try initializing the SDK as early in your app as possible, before the other parts of the app fragment the address space too much.

**Comment by vg-identance** [comment]
Oh, thanks! Will try 👍

**Comment by Cerovec** [comment]
Hi @vg-identance,

Did you try with the newest versions of BlinkID? 

Our runner should now be much more memory efficient than before.

Thanks,
Jurica.

**Comment by Cerovec** [comment]
Hi @vg-identance.

can I ask you to double-check if the latest releases help you with this issue? We haven't had any complaints so far after we improved the memory management in v5.1, and even more in the latest releases.

Thanks,
Jurica.

**Comment by vg-identance** [comment]
@vg-identance yes this seems work fine, thanks!

**Comment by Cerovec** [comment]
Excellent, thanks for the feedback!

We're closing this one. If you need anything else, please open another issue.

Thanks!
Jurica.
