### ISSUE TITLE
Disabling console logs does not work

### ISSUE THREAD

**Issue by leszek-s** [BlinkID/blinkid-ios#312]
There is no possibility to disable console logs. Implementing delegate methods from MBLoggerDelegate as suggested does not work. Moreover this delegate cannot be implemented in Swift language because it uses va_list parameter in delegate method which in Swift causes error "Method cannot be an implementation of an @objc requirement because the type of the parameter 3 cannot be represented in Objective-C".

**Comment by mparadina** [comment]
Hi @leszek-s 

You are correct. Currently, you can't implement the delegate in Swift.
However, in the upcoming releases, we will add a Swift compatible option for the `MBLoggerDelegate` .

If this issue is of urgent priority for you, and you can't wait for the upcoming releases, 
I recommend taking a look at this StackOverflow inquiry where there is an explanation on how you invoke an Objective-C variadic method from Swift:
https://stackoverflow.com/questions/24195796/how-do-you-call-an-objective-c-variadic-method-from-swift

Hope this helps,
Milan

**Comment by leszek-s** [comment]
Unfortunately this does not fix the problem as disabling logs does not work even if you try to do that in objective-c.

**Comment by mparadina** [comment]
Hi @leszek-s 

In the next release, we will provide a similar method that will enable you to disable the console logs.
The release should approximately come out in two weeks with the feature.

Hope this helps. If you have any additional questions, feel free to ask.

Regards,
Milan

**Comment by juraskrlec** [comment]
Hi @leszek-s 

We've just released v5.7.1 and in that version, you can use disbleMicroblinkLogging method on MBLogger class to disable Microblink logging in Swift.

Jura

**Comment by mparadina** [comment]
Hi @leszek-s 

Just following up on this thread.

Did you manage to disable the logs with the 5.7.1 version?

If you have any additional questions, feel free to ask.

Regards,
Milan

**Comment by mparadina** [comment]
Hi @leszek-s 

Since this issue is inactive, I am closing it.

If anything comes up, feel free to re-open the issue, or contact us directly at support@microblink.com

Regards,
Milan
