### ISSUE TITLE
Unable to scan Argentinian national ID

### ISSUE THREAD

**Issue by lucas-kummerle-perger** [BlinkID/blinkid-ios#317]
### Step 1: Are you in the right place?

  - For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with `BlinkID` and `Microblink` tags.

  - For issues or feature requests related to **the code in this repository**
    file a Github issue.

  - For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Microblink support](https://help.microblink.com/).

### Step 2: Describe your environment

  - Xcode version: 11.6
  - BlinkID SDK version: 5.5.0
  - What are you trying to scan: Argentinian national ID

### Step 3: Describe the problem

We are using the `MBBlinkIdCombinedRecognizer` to try to scan the Argentinian national ID. We use the `MBCustomOverlayViewController` `scanningRecognizerRunnerViewControllerDelegate` to get notified of a finished  scan of the front page with this method: `recognizerRunnerViewController:(nonnull UIViewController<MBRecognizerRunnerViewController> *)recognizerRunnerViewController didFinishScanningWithState:(MBRecognizerResultState)state;`. It is not called, even though this works for other documents. 
We also see variations of this in the console while scanning the document: `ZXing failure`

### Step 4: Relevant code

see above

**Comment by mparadina** [comment]
Hi @lucas-kummerle-perger 

Apologizes for the delay in our response.

Are you still experiencing issues with the mentioned document?

If I correctly understood your inquiry, you successfully scan the front side of the document, but the backside scanning does not trigger?

If this is the case, the reason for this is because we currently do not support the backside extraction of the Argentinian ID. 

You can see the full list of which documents we currently support with the BlinkID recognizer here:
https://github.com/BlinkID/blinkid-ios/blob/master/documentation/BlinkIDRecognizerResult.md

Which information do you require on the backside for your use-case?

Regards,
Milan

**Comment by lucas-kummerle-perger** [comment]
Hi @mparadina

Thanks, the issue has now been resolved as the the document scans as expected.
