### ISSUE TITLE
Error while compiling sample projects

### ISSUE THREAD

**Issue by aminiz** [BlinkID/blinkid-ios#35]
I downloaded the repo and compiling any of the sample projects gives me the following errors:

ld: warning: ignoring file ../../MicroBlink.framework/MicroBlink, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (arm64): ../../MicroBlink.framework/MicroBlink
Undefined symbols for architecture arm64:

I am using Xcode 7. Any suggestions?

**Comment by Pickles112358** [comment]
This error is probably related to Git LFS. The problem is that your MicroBlink.framework/MicroBlink file did not download correctly (it probably has size of less than a 1KB). To fix this issue you can:
- Download .zip of our latest release instead : https://github.com/BlinkID/blinkid-ios/releases/download/v2.2.1/BlinkID-ios_v2.2.1.zip

OR

- Follow our "Getting Started" guide: https://github.com/BlinkID/blinkid-ios/wiki/Getting-started
Pay close attention to parts related to Git LFS

Let me know if you need any more help!

Kind regards,
Dino

**Comment by aminiz2** [comment]
Downloading the latest zip worked. Thank you for the prompt response and solution.

**Comment by Philipp372** [comment]
Hello,
I had the same problem and the alternative link you provided works. Pls notice that on the main download link for the zip file (main page -> "Clone or download") the issue still remains, which may lead to more people stepping into this issue when trying out your product.

**Comment by Pickles112358** [comment]
You are correct.
The problem here is that GitHub does not fully support Git LFS and unfortunately we cannot override the function of "Clone or download" button.

**Comment by mjurfest** [comment]
Hi @culoi, can you please provide the new link to download? I tried the last one but the license key is not valid anymore.

**Comment by culoi** [comment]
Hi @mjurfest 

You can generate the demo key on our dashboard: www.microblink.com/login 

Also, the link for the SDK releases is available here: https://github.com/BlinkID/blinkid-ios/releases

Regards

**Comment by Brankacro** [comment]
Hi @mjurfest,

hope everything goes well.
I am closing this issue. In case you have any questions or require assistance, feel free to contact us.
