### ISSUE TITLE
Detecting EUDL reliably in v5 as it used to in v4

### ISSUE THREAD

**Issue by MyBuzzTechnologies** [BlinkID/blinkid-ios#350]
We're upgrading to BlinkID 5.11 from v4.9 and are having problems detecting when a scan completes for a UK Driving License as you've removed a class for reasons I can't understand.

We used to use the EUDLRecognizer which worked well but this isn't available in the v5 SDK.

The ClassInfo object in the MBRecognizerResult object seems to be the correct way to detect the different classifications of the detected document but there's only IDCard, which covers too many different types.

I'm currently checking whether there are any populated fields in driverLicenseDetailedInfo (plus the country code in ClassInfo) but this is a terrible solution and much worse than the v4 SDK solution.

Is there a way to reliably detect the recognised document as a UK Driving License?
If not, is this on your roadmap to correct and do you an estimated date for release?

**Comment by mparadina** [comment]
Hi @MyBuzzTechnologies 

Thank you for waiting for our response.

BlinkID v5 is powered entirely by machine learning and we've made some significant improvements to the SDK when it comes to accuracy in document reading and extraction, and the overall SDK performance when compared to version 4.9. 
In version 5, you only need one recognizer to scan and extract information from multiple documents.

You can see all of the documents you can read with the BlinkID (Combined) recognizer:
https://github.com/BlinkID/blinkid-ios/blob/master/documentation/BlinkIDRecognizerResult.md#all-fields

You are correct in how to detect the UK DL, you need to use the `classInfo` property in order to see which type and country is the document from.

You can, for instance, see if the scanned document is the UK DL this way after you scan the document:

```
  let result = self.blinkIdRecognizer?.result
  let classInfo = result?.classInfo
  
  if classInfo?.type == .typeDl && classInfo?.country == .UK {
      print("This is a DL from UK")
     }
```

With `classInfo`, you can also choose which documents you want to scan and filter out. 
For instance, you can modify the SDK to only read and extract the information if the document is a UK driver's license.

You can do that with the `MBBlinkIdRecognizerDelegate` if you are using the `MBBlinkIdRecognizer`.
Firstly, you need to add the MBBlinkIdRecognizerDelegate as an extension to your ViewController where you're doing the scanning process.

After that, you can add the method called `classInfoFilter` in which documents should be filtered out.

An example code would be:
```
extension ViewController: MBBlinkIdRecognizerDelegate {
    func classInfoFilter(_ classInfo: MBClassInfo?) -> Bool {
        if classInfo?.type == .typeDl && classInfo?.country == .UK {
     return true
     } else {
     return false
         }
       }
    }
```

In the example, the only type of documents that will pass the scanning process is the DL from UK.

However, you can filter out with other parameters, which can be found here:
http://blinkid.github.io/blinkid-ios/Classes/MBClassInfo.html

Lastly, need to add `classFilterDelegate` on the BlinkID recognizer to be `self`.

Example:
```
 self.blinkIdRecognizer = MBBlinkIdRecognizer()
 self.blinkIdRecognizer?.classFilterDelegate = self
```
Let me know if this helped.

Regards,
Milan

**Comment by MyBuzzTechnologies** [comment]
That's really helpful! Thank you for the fast and detailed response, it was just what I needed to know.

It would really great if your documentation could include details such as this to help those getting started with BlinkID as it isn't clear how to determine which document was detected (and the best way of going about it) from your official docs and Getting Started guides.
