### ISSUE TITLE
embedded framework support on iOS7

### ISSUE THREAD

**Issue by sarn** [BlinkID/blinkid-ios#4]
the microblink sdk is included into the sample project in the form of an embedded framework. Embedded Frameworks apparently only work on iOS8 and up. But you state that blinkid-ios can be used starting from iOS6 and up. Do I miss something?

**Comment by Cerovec** [comment]
Hi Sarn,

embedded framework format used by BlinkID is an old trick to make Xcode see included resources together with library and header files. As far as Xcode is concerned, framework contains simply folders. The library itself is a relocatable object file. This trick was working since iOS 4, and it was the easiest way to ship SDK products before iOS 8.

With iOS 8, Apple introduced real embedded frameworks. They were introduced mainly to support development of app extensions, they are supported by Xcode by default, and use dylib format of the library.

It's true that apps using iOS 8 embedded frameworks can't support previous versions of iOS. That's why in our products, we're sticking to old and tested solution.
