### ISSUE TITLE
Does not detect anything on iPad Air

### ISSUE THREAD

**Issue by arnolddrita** [BlinkID/blinkid-ios#45]
I've downloaded the sample project, and run it on two devices so far. The same build, when run on an iPhone 6, works perfectly and detects the ID card. When I run it on an iPad air, nothing happens. I've tried with different properties, but it never calls the method didOutputResults, nor does it call any other method or output any error. It just sits there, sometimes it shows the dots on the image that signal that it is scanning something, but that's about it.
I don't know how to debug this problem.

Thanks

**Comment by culoi** [comment]
Can you try with the iPad held closer to the DL?

On iPad our current frame for scanning is too small, and in the next update we'll be making it bigger. We think this affects the scanning.
Too big distance between the device and the card means that the card is smaller on the image, which means that the resolution with the scanning is too small, which makes the scanning harder.

Conversely, the device should not be held too close to the ID also, because on really small distances the camera cannot perform autofocus.

So, the distance should be just right.

Please try and let us know.

**Comment by Cerovec** [comment]
Hi Arnold,
2.6.0 now has larger frame for scanning on iPad. Please let us know if it works for you. If it does, please close this issue.
Thanks,
Jurica.

**Comment by Cerovec** [comment]
Closed since the issue topic is related to positioning of the viewfinder, which was improved in v2.6.0. Thanks!
