### ISSUE TITLE
Orientation changes

### ISSUE THREAD

**Issue by vladimirzivanov** [BlinkID/blinkid-ios#49]
How to support orientation changes? I found this
`
supportedInterfaceOrientations() -> UIInterfaceOrientationMask {
 return UIInterfaceOrientationMask.Landscape;
}
` 
 but i don't know how to use this. And how to change scaning region after orientation change?

**Comment by Cerovec** [comment]
Hi Vladimir,

if you have your custom scanning region, I assume you're also using custom UI integration, because the UI should display the limits of the scanning region so that the user can aim in the direction of the document. One without the other doesn't make much sense.

Then in your custom overlay view controller, you simply handle the orientation change like in any other View controller. It's also important that you update the scanning region when the size of the view changes (this can be done for example in viewWillLayoutSubviews method).

Since OverlayViewController is actually a child view controller to the CameraViewController responsible for presenting the camera, you should also specify which orientations does the CameraViewController support. This is done using `autorotate` and `supportedOrientations` properties of the [CameraViewController](http://cocoadocs.org/docsets/PPBlinkID/2.5.1/Protocols/PPScanningViewController.html#//api/name/autorotate).

Simply set it to 
- autorotate = YES
- supportedInterfaceOrientations = UIInterfaceOrientationMask.Landscape to support both landscape orientations.

PS. this makes sense if you present the camera view controller modally using presentViewController method. If you use it in a container view controller (such as UINavigationController), then the container is responsible for orientation changes.

Best,
Jurica.

**Comment by vladimirzivanov** [comment]
Thank you, it works. Now i have another problem, when start default camera app terminating and i got this message _*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Zicer model must not be null!'_  . Camera appears and then the application breaks.  Can you help me with this?

**Comment by vladimirzivanov** [comment]
It helped me, thanks.
