### ISSUE TITLE
dewarpedImage not returned for eudl

### ISSUE THREAD

**Issue by mvayngrib** [BlinkID/blinkid-ios#50]
maybe i'm not clear on the difference between:

```obj-c
settings.metadataSettings.dewarpedImage = YES
```

and

```obj-c
eudlRecognizerSettings.showFullDocument = YES
```

i'm currently using the former, but i guess should be using both? I don't see a corresponding value for usdl. Is that because on the usdl only the barcode is scanned?

**Comment by culoi** [comment]
Hello mvayngrib,

The line
```
   settings.metadataSettings.dewarpedImage = YES
```
will enable receiving of [PPImageMetadata](http://cocoadocs.org/docsets/PPBlinkID/2.5.1/Classes/PPImageMetadata.html) in ScanDelegate's [didOutputMetada](http://cocoadocs.org/docsets/PPBlinkID/2.5.1/Protocols/PPScanningDelegate.html#//api/name/scanningViewController:didOutputMetadata:). Without this enabled, images will not arrive to the callback.

The line
```
   eudlRecognizerSettings.showFullDocument = YES
```
will tell [EUDL recognizer](http://cocoadocs.org/docsets/PPBlinkID/2.5.1/Classes/PPEudlRecognizerSettings.html) to send the image of the full document to the ScanDelegate. So, you need both those enabled to be able to obtain images.

Considering the USDL, since [USDL recognizer](http://cocoadocs.org/docsets/PPBlinkID/2.5.1/Classes/PPUsdlRecognizerSettings.html) reads all information from [PDF417 barcode](https://en.wikipedia.org/wiki/PDF417), it does not have support for returning dewarped image of the document, since the barcode can be read directly in the original image - no dewarping required.

However, if you still need to obtain the full document image of the US Driver's License, you can use [Detector recognizer](http://cocoadocs.org/docsets/PPBlinkID/2.5.1/Classes/PPDetectorRecognizerSettings.html). You can see an example of how this can be done in [this demo app](https://github.com/BlinkID/blinkid-ios/tree/master/Samples/Detector-sample).

**Comment by mvayngrib** [comment]
@culoi awesome, that clears things up for me!
