### ISSUE TITLE
Umbrella framework, 'MicroBlink' is sub-framework

### ISSUE THREAD

**Issue by vladimirzivanov** [BlinkID/blinkid-ios#51]
Is it posible to add 'MicroBlink' into myFramework as a sub-framework and users only need to import myFramework in their project. In other words, myFramework will work as a wrapper for 'MicroBlink'.

**Comment by culoi** [comment]
@vladimirzivanov it should be possible. Please try and if you have and additional questions, do not hesitate to ask.

**Comment by vladimirzivanov** [comment]
I added 'MicroBlink' in my frameworks as a sub-framework and when i import my framewok in app i can't build, looking for MicroBlink. But when i add 'Microblink' in Linked Frameworks and libraries then compile fine and have no errors. When run app and call camera from framework app crashed, then add MicroBlink.bundle in Copy Bundle Resources and than all works fine and I can use MicroBlink normally. How to connect MicroBlink framework and MicroBlink bundle with my framework, so i don't have to do anything in main app?

**Comment by Cerovec** [comment]
Hi Vladimir,

if you added Microblink framework in the linked frameworks, then yes, you will need to link the final app once again with our framework.

You have an option to link with our framework as a static library, by using -l linker option, and specifying header search path and library search paths. Then our framework will be "compiled into" your framework. This would be our recommendation.

You can also prelink our framework (prelink libraries build settings). 

For the bundle, it's necessary that Microblink.bundle is located in the main bundle of the app when the application runs. That's a requirement, because our SDK needs the files in the bundle to work properly. Do you have any preferred ways how you would work around this?

Thanks,
Jurica.

**Comment by Cerovec** [comment]
Hi Vladimir,

please check if the new PPSettings [resourcesBundle](https://github.com/BlinkID/blinkid-ios/blob/master/MicroBlink.framework/Headers/PPSettings.h#L83-L92) feature satisfies your requirements. If it doesn't, please let us know, otherwise we should close this issue.

Thanks,
Jurica.
