### ISSUE TITLE
Link Error on install cocoapods

### ISSUE THREAD

**Issue by KingAndroid** [BlinkID/blinkid-ios#57]
I'd like to make card app using this sd.
But for now I got link error.

Please check below screenshot.
How could i resolve it?
Thanks.
![1](https://cloud.githubusercontent.com/assets/4363735/22617606/490a4d82-eb04-11e6-8d16-57f2af5a8f4a.png)

**Comment by culoi** [comment]
Hi @KingAndroid ,

please install git lfs (as described in our documentation - https://github.com/BlinkID/blinkid-ios#installation-with-cocoapods)

Also, please take a look on the issue we already had reported: https://github.com/BlinkID/blinkid-ios/issues/27

This issue is related to the fact that git lfs was not installed when the project was pulled from the github.

Let us know if this helps.

**Comment by Cerovec** [comment]
Please let us know if you still have this issue. Otherwise, close it.
Thanks,
Jurica.

**Comment by juraskrlec** [comment]
Closed as inactive
