### ISSUE TITLE
Scanning front of USDL doesn't work, but backside works perfectly fine

### ISSUE THREAD

**Issue by charleshkang** [BlinkID/blinkid-ios#61]
Hi there,

I've been implementing ID verification for driver's licenses. After getting it to work, I'm finding that while front ID scanning doesn't work, I can get all the info I need from scanning the barcode on the back of the driver's license. 

Is this expected behavior? Scanning the back of the ID is extremely quick so it's working, it's just odd that front ID scanning doesn't work. 

I'm assuming all info is contained in the barcode, but I've only tried a NY state license, and am not sure if it'll differ state to state. It look like the info scanned through the barcode differs state to state so...any help would be appreciated! 

Edit: I've also tried the newest version through CocoaPods, front facing scan still doesn't work through my implementation

Is it possible to add custom text on the scan screen? Using `PPCameraOverlayViewController`

**Comment by Cerovec** [comment]
Hi Charles,

yes - it's by design. We're working on support for scanning front side of the IDs, but we'll need examples of ID cards which we can work on improving the support. Any help here would be much appreciated.

So far, from the front side, you can extract the photo of the front side of the ID, and the face photo, using PPDocumentFaceRecognizer (settings and result).

Would this work for you?

**Comment by charleshkang** [comment]
Thanks @Cerovec, that's helpful. I'll give that a shot!

**Comment by charleshkang** [comment]
Closing this now, thanks again for the help!
