### ISSUE TITLE
Failing to compile on CircleCI

### ISSUE THREAD

**Issue by benaneesh** [BlinkID/blinkid-ios#63]
Trying to get my builds tested using CircleCi. They compile and pass locally, but on their server it keeps failing to compile with this error:

```
❌  Undefined symbols for architecture x86_64
> Symbol: _kPPCustomerFullName
> Referenced from: static Cover.LicenceInfo.initWithUSDLResult (__ObjC.PPUsdlRecognizerResult) -> Cover.LicenceInfo in LicenceInfo.o

❌  ld: symbol(s) not found for architecture x86_64

❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

CircleCi has git-lfs installed already, so just to make sure, added this to the `circel.yml` file:
```
dependencies:
  override:
    # Install git-lfs
    - brew install git-lfs
```

But the test failed with:
```
Error: git-lfs-1.5.0 already installed
To install this version, first `brew unlink git-lfs`
```

So its safe to say that the error is not with `git-lfs`.

Installed using:
```
pod 'PPBlinkID', '~> 2.4.0'
```

Since it compiles locally, is there any dependency that I am missing?

**Comment by Cerovec** [comment]
Hi,

this linker error means either this one specific name is missing (which can idicate that we failed to expose that string), or that the whole Microblink.framework is not checked out. 

Does the linker complain about all symbols (indicating a missing Microblink.framework because of git lfs), or just one specific symbol?

Most likely it's an issue with git lfs (we had similar problems on Travis CI).

We don't have expeirence with CircleCI, but on Travis we managed to get the build working by ensuring `git lfs pull` is called in the before script. Also, there we don't have the project added as a pod, but directly linked with the library.

Also, can you please share your circle.yml file?

Thanks!
Jurica.

**Comment by benaneesh** [comment]
Apologies for the late reply. Heres the `circle.yml` file:

```
machine:
  environment:
    GYM_CODE_SIGNING_IDENTITY: "<OUR_IDENTITY>"
  xcode:
    version: 8.2
test:
  override:
    - bundle exec fastlane test
```

**Comment by Cerovec** [comment]
Hi,
@juraskrlec is looking into this. We'll let you know when we have some results.
Thanks,
Jurica.

**Comment by juraskrlec** [comment]
Hi,
we've successfully tested Circle CI integration. This shows that blinkid sdk works with CircleCI. In branch `feature/circleci ` you can see scripts and `circle.yml` file we've used for integration. In folder **circleci** there are 2 scripts:` before_script.sh` and `script.sh`. Add ` before_script.sh` path to **Dependency Commands/Dependency overrides** and `script.sh` path to **Test commands**.
Please let us know what's the difference between this and your project.
Thanks,
Jura

**Comment by benaneesh** [comment]
Thanks @Cerovec and @juraskrlec , appreciate the help.

Will test with these scripts and let you know.

**Comment by Cerovec** [comment]
Do you have any news with this? :)

**Comment by juraskrlec** [comment]
Closing as inactive

**Comment by OlegPanfyorov** [comment]
@juraskrlec Hi man got the same problem but feature/circleci branch with scripts no longer exist. Could you send please the solution once again with scripts content?
