### ISSUE TITLE
version 2.8.0 breaks after updating from 2.7.1 - libz linker issue

### ISSUE THREAD

**Issue by hollowaykeanho** [BlinkID/blinkid-ios#81]
A quick question, is version 2.8.0 backward compatible? I'm getting this message after upgraded to version 2.8.0.

<img src="https://lh3.googleusercontent.com/KtcsOMh632oS_WOUwzOfWNsUpl3jBZG7qe6y5qD3g5hmM4ISFYldf86mjqF1TuTWuK_x0quC9iLF1iB0BdqVCXJIEG6xEH39gQ_FGAQg-q1_bjOjqfFbF0-7E7cz9TGkXU0TwLfOXNAszRE2K4A6iBR2qIOG_lwEzQaqa4SC1v9QZ2nmhuNTHOTIY-z-a6RnNdBiAE6gO-R30PjkEw5_yqJc2lKPfznunE--Md3a0YJMrfjSO7n6al1hwq8pNuwag67C69Ad5kizSe8err63H-PgNdOA3YUqpNx8_ZdEe5q_FB73IjyWjKOtHEAScFNVdX4P6ZEtSkvr1VAysbUmxaAcWDht_dWo2sRwkkCMVTcUQQcOpN3REe6q1wFhcrcqkURw-DRnYf8q84arlgHLeODvrItsUeORjTWD3L0MAwe-KHiaSgDCYmT3G3adCSTHKX1mH39IeYJ3ub5qPdUmoYyTkk4JL0WabOtIjALLHzf1eTXCUeq7bo3sJ-VtSlvX1PpyaFjs8UnMXel8Au619JYlgwMkfFGw39si9Ak4f07bK2qzVgubSItoUo0QOvfKyjvXP-mYQravVAeDOa9NnC61D71rGxotfzwijyNrCCZPzl2X9yuxyP7c8yIckrGm5VVRjC0M5q_HxcD0fGqRoQ19Mk3fAnOwfxJ2Rf2Z4g=w1478-h930-no" />

Occurs even after deleting the Derived Data folder.

**Comment by hollowaykeanho** [comment]
Issue found after reading the Release Note for version 2.8: 
> Added libz to all samples to prevent linker errors (caused by slimming down the SDK)

<br/>
After adding `libz.tbd` manually into `Linked Frameworks and Libraries`, the issue resolved on its own.

This is definitely a bug caused by slimming down the SDK effort.

**Comment by Cerovec** [comment]
Hi,

in the process of slimming down - we eliminated some of the libraries which were not necessary to add inside our SDK. libz is one of them. iOS allows you to link with dynamic library which is part of the OS. 

We don't intend to re-add libz into our SDK as this would be a step back.

We hope this makes sense to you.

**Comment by hollowaykeanho** [comment]
Hello @Cerovec,

It is a good effort in slimming down the SDK. Thanks though. However, I believe the documentations in the [Getting Started](https://github.com/BlinkID/blinkid-ios/wiki/Getting-started) section is outdated, hence, this issue exists. It took me some hours to study the cause.

p/s: Please don't do a re-add. The current way is better than before as it is more transparent on our side.

**Comment by michael-mckenna** [comment]
![screen shot 2017-05-21 at 3 31 52 pm](https://cloud.githubusercontent.com/assets/14035148/26287148/aae74f4e-3e3a-11e7-9c91-e471355bb5a5.png)

Getting this error. Any solutions?

**Comment by hollowaykeanho** [comment]
@michael-mckenna , have you tried add `libz` into your framework?

**Comment by Cerovec** [comment]
@michael-mckenna - this looks like a git lfs issue. We have our binary stored in git lfs, and git lfs is required to check it out from git.

Do you have git lfs installed?
Can you send us the output of git lfs command in terminal?

**Comment by michael-mckenna** [comment]
@hollowaykeanho Yep. Under Targets -> AppName -> Lined Frameworks and Libraries I added libz.tbd.

**Comment by michael-mckenna** [comment]
@Cerovec Yes git lfs is installed.

git-lfs/2.1.1 (GitHub; darwin amd64; go 1.8.1)
git lfs <command> [<args>]

Git LFS is a system for managing and versioning large files in
association with a Git repository.  Instead of storing the large files
within the Git repository as blobs, Git LFS stores special "pointer
files" in the repository, while storing the actual file contents on a
Git LFS server.  The contents of the large file are downloaded
automatically when needed, for example when a Git branch containing
the large file is checked out.

Git LFS works by using a "smudge" filter to look up the large file
contents based on the pointer file, and a "clean" filter to create a
new version of the pointer file when the large file's contents change.
It also uses a pre-push hook to upload the large file contents to
the Git LFS server whenever a commit containing a new large file
version is about to be pushed to the corresponding Git server.

Commands
--------

Like Git, Git LFS commands are separated into high level ("porcelain")
commands and low level ("plumbing") commands.

High level commands 
--------------------

* git lfs env:
    Display the Git LFS environment.
* git lfs checkout:
    Populate working copy with real content from Git LFS files
* git lfs clone:
    Efficiently clone a Git LFS-enabled repository
* git lfs fetch:
    Download git LFS files from a remote
* git lfs fsck:
    Check GIT LFS files for consistency.
* git lfs install:
    Install Git LFS configuration.
* git lfs lock:
    Set a file as "locked" on the Git LFS server.
* git lfs locks:
    List currently locked files from the Git LFS server.
* git lfs logs:
    Show errors from the git-lfs command.
* git lfs ls-files:
    Show information about Git LFS files in the index and working tree.
* git lfs pull:
    Fetch LFS changes from the remote & checkout any required working tree files
* git lfs push:
    Push queued large files to the Git LFS endpoint.
* git lfs status:
    Show the status of Git LFS files in the working tree.
* git lfs track:
    View or add Git LFS paths to Git attributes.
* git lfs unlock:
    Remove "locked" setting for a file on the Git LFS server.
* git lfs untrack:
    Remove Git LFS paths from Git Attributes.
* git lfs update:
    Update Git hooks for the current Git repository.
* git lfs version:
    Report the version number.
  
Low level commands 
-------------------

* git lfs clean:
    Git clean filter that converts large files to pointers.
* git lfs pointer:
    Build and compare pointers.
* git lfs pre-push:
    Git pre-push hook implementation.
* git lfs smudge:
    Git smudge filter that converts pointer in blobs to the actual content.

**Comment by Cerovec** [comment]
Now while in blinkid-ios repository, enter `git lfs pull`.

File Microblink.framework/Microblink should now have more than 100MB (without git lfs it had less than 1kB).

Please verify that file size.

**Comment by Cerovec** [comment]
@michael-mckenna - do you have any news with this?

Also, since this is not releated to the original question, we can move this to a separate issue, if it still persists.

**Comment by michael-mckenna** [comment]
Turns out I accidentally installed it first without git LFS. I cleared the cocoa pods cache and reinstalled the pod and it worked

**Comment by juraskrlec** [comment]
Closed as solved
